# Generated by Django 3.1.4 on 2020-12-16 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WMHeader',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('pname', models.CharField(db_column='pname', max_length=50)),
                ('pdesc', models.CharField(db_column='pdesc', max_length=255)),
            ],
            options={
                'db_table': 'wm_qheader',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WMQuestion',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('parent_id', models.IntegerField(db_column='parent_id', default=0)),
                ('qlevel', models.IntegerField(db_column='qlevel', default=1)),
                ('order_no', models.IntegerField(db_column='order_no', default=1)),
                ('qname', models.CharField(db_column='qname', max_length=50)),
                ('qdesc', models.CharField(db_column='qdesc', max_length=255)),
            ],
            options={
                'db_table': 'wm_question',
                'managed': False,
            },
        ),
    ]
