# Generated by Django 3.1.4 on 2020-12-26 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CBCodeDtl',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('type_cd', models.CharField(db_column='type_cd', max_length=20)),
                ('code_cd', models.CharField(db_column='code_cd', max_length=20)),
                ('code_name', models.CharField(db_column='code_name', max_length=50)),
                ('register_date', models.DateTimeField(db_column='register_date')),
                ('usage_flag', models.CharField(db_column='usage_flag', default='1', max_length=10)),
            ],
            options={
                'db_table': 'cb_code_dtl',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CBCodeHdr',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('type_cd', models.CharField(db_column='type_cd', max_length=20)),
                ('type_name', models.CharField(db_column='type_name', max_length=50)),
                ('register_date', models.DateTimeField(db_column='register_date')),
                ('usage_flag', models.CharField(db_column='usage_flag', default='1', max_length=10)),
            ],
            options={
                'db_table': 'cb_code_hdr',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CBItemgrp',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('itemgrp_cd', models.CharField(db_column='itemgrp_cd', max_length=20)),
                ('itemgrp_name', models.CharField(db_column='itemgrp_name', max_length=255)),
            ],
            options={
                'db_table': 'cb_itemgrp',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CMFactory',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('factory_cd', models.CharField(db_column='factory_cd', max_length=20)),
                ('factory_name', models.CharField(db_column='factory_name', max_length=255)),
            ],
            options={
                'db_table': 'cm_factory',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CMItem',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('unit_id', models.IntegerField(db_column='unit_id', default=0)),
                ('item_cd', models.CharField(db_column='item_cd', max_length=20)),
                ('item_name', models.CharField(db_column='item_name', max_length=255)),
                ('item_spec', models.CharField(db_column='item_spec', max_length=255)),
                ('register_date', models.DateTimeField(db_column='register_date')),
                ('usage_flag', models.CharField(db_column='usage_flag', default='1', max_length=10)),
            ],
            options={
                'db_table': 'cm_item',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CMItemaccnt',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('itemaccnt_cd', models.CharField(db_column='itemaccnt_cd', max_length=20)),
                ('itemaccnt_name', models.CharField(db_column='itemaccnt_name', max_length=255)),
            ],
            options={
                'db_table': 'cm_itemaccnt',
                'managed': False,
            },
        ),
    ]
