# Generated by Django 3.2.3 on 2021-08-16 03:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membername', models.CharField(db_column='membername', default='', max_length=50)),
                ('role', models.CharField(choices=[('user', 'user'), ('manager', 'manager'), ('partner', 'partner')], default='user', max_length=20)),
                ('phone_no', models.CharField(db_column='phone_no', default='', max_length=100, null=True)),
                ('zipcode', models.CharField(db_column='zipcode', default='', max_length=10, null=True)),
                ('address', models.CharField(db_column='address', default='', max_length=1024, null=True)),
                ('address_detail', models.CharField(db_column='address_detail', default='', max_length=255, null=True)),
                ('usage_flag', models.CharField(default='1', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
